version: '3'
services:
  app:
    image: sonalyzebot/sonalyze:test
    restart: always
    ports:
      - '10001:8000'
    networks:
      - sonalyze-test

networks:
  sonalyze-test:
    external: true